name: Testing GitHub Actions

on:
  push:
    branches: [ master, main, dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set env to for main
        if: endsWith(github.ref, '/main')
        env:
          MYENVVAR: "for main environment"
        run: |
          echo "====================================="
          echo $MYENVVAR
          echo "====================================="

      - name: Set env to for dev
        if: endsWith(github.ref, '/dev')
        env:
          MYENVVAR: "dev is here"
        run: |
          echo "====================================="
          echo $MYENVVAR
          echo "====================================="
