name: Testing GitHub Actions

on:
  push:
    branches: [ master, main, dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: npm run-script build
      
      - name: Set env to for main
        if: endsWith(github.ref, '/main')
        env:
          MYENVVAR: "for main environment"
        run: |
          echo "====================================="
          echo $MYENVVAR
          echo "====================================="

      - name: Set env to for dev
        if: endsWith(github.ref, '/dev')
        env:
          MYENVVAR: "dev is here"
        run: |
          echo "====================================="
          echo $MYENVVAR
          echo "====================================="

      - name: Set env to for master
        if: endsWith(github.ref, '/master')
        env:
          MYENVVAR: "master is here"
        run: |
          echo "====================================="
          echo $MYENVVAR
          echo "====================================="

      - name: Set env to for other branch
        if: (!endsWith(github.ref, '/master') && !endsWith(github.ref, '/dev') && !endsWith(github.ref, '/dev'))
        env:
          MYENVVAR: "this is other branch"
        run: |
          echo "====================================="
          echo $MYENVVAR
          echo "====================================="
